name: Publish to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install Deps
      run: npm install

    - name: Build
      run: npm run build
      
    - name: Upload Dist Folder
      uses: actions/upload-artifact@v4
      with:
        path: './dist/*'
        name: 'github-pages'
  deploy:
    needs: build
    
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
